name: Fly.io Usage Limit

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC 执行一次
  workflow_dispatch:

jobs:
  limit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check usage and stop machine if needed
        run: |
          python3 limit.py
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
