name: Start Machine (Daily)

on:
  schedule:
    - cron: "0 1 * * *"   # 每天 UTC 01:00，即北京时间 09:00
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Start machine
        run: flyctl machines start 1781e7e4a27328 --app fly-easytier-ipv4
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
