name: Stop Machine (Saturday)

on:
  schedule:
    - cron: "30 3 * * 6"   # 周六 11:30 停机（运行 2.5 小时）
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Stop machine
        run: flyctl machines stop --app fly-easytier-ipv4
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
